language: python
sudo: false
cache:
  directories:
  - container
python:
- '2.7'
- '3.4'
- pypy
env:
  matrix:
  - CMAKE_VERSION="latest"
  - CMAKE_VERSION="3.0"
  - CMAKE_VERSION="2.8"
  global:
    secure: ChZoff0thvWQHK8pfab3oaxPgud0e365g/YO7MYJ2HwWBTP9Gq96mrhganYXneKlb4YfEIN27k6XjNIDFK+Oe+Q8L/8LHU2XMdjjBtyMG7Hm6vge9Ik6oq34zC5RsTttgNs4yrq1VFcfqwMvif4kW0+LitJ5WCkpjCVQ+8RXBnU=
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s container-setup.py -e bash -p /dev/stdout --cmake-version
  ${CMAKE_VERSION})
script:
- polysquare_run check/python/check.py
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/python/coverage.py
before_deploy:
- polysquare_run deploy/python/deploy.py
deploy:
  provider: pypi
  user:
    secure: n+N1B9CiMyHM2SMdkCfRqUk7CIWYA9mtlez7lQW7iCLQNYCvEoZprvUnlvUlKUdafwBWi543Ezes+VTm3cyC9NoTL/NKfFZ4J8ZpBl4JGJJNfnKlXjBsmp2LFCySDVFwft1ed9miIjqkzsYTD2ohyBX+An70yfxMHfQ5DnS3D1Y=
  password:
    secure: i6YvJQnKlOj7kGVUwLn4gL6gYRPoX83IYusz/8GUyA8wz3p3Uiu5jtWwqpu3/U538ESfGFhbaj2bf9VtVbixpk/8+MrGYBVGM+42MB9VpLd6sADe0dqoyW2+yIgodeoLNxBKhK8wg0jVmEtSzRQuakSijlpWF+Pj9lit4GEhBcA=
  on:
    repo: polysquare/cmake-ast
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7" && $CMAKE_VERSION = "latest"
