environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python27"

cache:
 - C:\container -> appveyor.yml
 - C:\Python34 -> appveyor.yml
 - C:\Python27 -> appveyor.yml

install:
 - ps: $env:PATH="${env:PYTHON};${env:PYTHON}/Scripts;${env:PATH};C:/MinGW/bin;C:/Python34;C:/Python34/Scripts"
 - ps: $env:POLYSQUARE_PREINSTALLED_PYTHONS="C:\Python34;C:\Python27"
 - ps: wget public-travis-scripts.polysquare.org/bootstrap.py -OutFile bootstrap
 - ps: python bootstrap -d C:/container -s container-setup.py -e powershell -p test-env.ps1 --no-mdl
 - ps: . ./test-env

build: false

test_script:
 - ps: polysquare_run check/python/check.py --no-mdl

after_test:
 - ps: polysquare_cleanup
